version: '3'
services:
  jitsi-meet-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: webtv/jitsi-meet-api
    container_name: jitsi-meet-api
    ports:
      - "9998:8095"
    volumes:
      - ${WEBINAR_HTDOCS}:/var/www/webinar-conf-beta.webtv-solution.com/htdocs
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock:ro
      - /var/www/webinar-recordings/:/var/www/webinar-recordings/
      - .:/go/src/gitlab.webtv-solution.com/webtvpro/jitsi_meet_config_api
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      WEBINAR_RECORDINGS_DIRECTORY: /var/www/webinar-recordings/
      PIPER_UPLOAD_ENDPOINT: http://dev01.webtv-solution.com:8765/api/assets/upload
      PIPER_TRANSCODE_ENDPOINT: http://dev01.webtv-solution.com:8765/api/transcode
      TOKEN: ${TOKEN}
    networks:
      meet.jitsi:

networks:
  meet.jitsi:
    external: true